-- Event Booking System Database Schema
-- Oracle Database XE
-- CS313 Advanced Programming Language Project

-- Drop existing tables if they exist (for clean setup)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE BOOKINGS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE EVENTS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE USERS CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

-- Drop existing sequences if they exist
BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE USER_SEQ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE EVENT_SEQ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP SEQUENCE BOOKING_SEQ';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

-- Create Sequences for primary keys
CREATE SEQUENCE USER_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE EVENT_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

CREATE SEQUENCE BOOKING_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- Create USERS table
CREATE TABLE USERS (
    USER_ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(50) UNIQUE NOT NULL,
    PASSWORD VARCHAR2(50) NOT NULL,
    FULL_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100),
    ROLE VARCHAR2(20) NOT NULL CHECK (ROLE IN ('Customer', 'Manager', 'Admin'))
);

-- Create EVENTS table
CREATE TABLE EVENTS (
    EVENT_ID NUMBER PRIMARY KEY,
    EVENT_NAME VARCHAR2(100) NOT NULL,
    EVENT_DATE DATE NOT NULL,
    LOCATION VARCHAR2(200) NOT NULL,
    DESCRIPTION VARCHAR2(500),
    TOTAL_CAPACITY NUMBER NOT NULL CHECK (TOTAL_CAPACITY > 0),
    SEATS_REMAINING NUMBER NOT NULL CHECK (SEATS_REMAINING >= 0),
    TICKET_PRICE NUMBER(10,2) NOT NULL CHECK (TICKET_PRICE >= 0),
    MANAGER_ID NUMBER,
    CONSTRAINT FK_MANAGER FOREIGN KEY (MANAGER_ID) REFERENCES USERS(USER_ID) ON DELETE SET NULL
);

-- Create BOOKINGS table
CREATE TABLE BOOKINGS (
    BOOKING_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER NOT NULL,
    EVENT_ID NUMBER NOT NULL,
    BOOKING_DATE DATE NOT NULL,
    NUMBER_OF_TICKETS NUMBER NOT NULL CHECK (NUMBER_OF_TICKETS > 0),
    CONSTRAINT FK_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE,
    CONSTRAINT FK_EVENT FOREIGN KEY (EVENT_ID) REFERENCES EVENTS(EVENT_ID) ON DELETE CASCADE
);

-- Display success message
SELECT 'Database schema created successfully!' AS STATUS FROM DUAL;
